#!/usr/bin/env node
/**
 * Imports the official penpot-ai-kit (https://github.com/penpot/penpot-ai-kit)
 * into the Penpot Skills platform scope.
 *
 * Converts every kit skill (skills/<id>/SKILL.md) plus the load-bearing shared
 * docs into our skill format (markdown + flat frontmatter, scope: platform,
 * enforcement: advisory, mode preserved) and generates
 * ../skills-core/src/aikit.gen.ts — the single platform-scope module shared
 * by the Skills plugin, the MCP server and the MCP plugin.
 *
 * Usage: node scripts/import-aikit.mjs [path-to-penpot-ai-kit-checkout]
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const kitDir = process.argv[2] ?? join(here, "..", "..", "..", "penpot-ai-kit");

if (!existsSync(join(kitDir, "skills.json"))) {
  console.error(`penpot-ai-kit checkout not found at ${kitDir}`);
  process.exit(1);
}

const kitManifest = JSON.parse(readFileSync(join(kitDir, "skills.json"), "utf8"));

/** Splits a kit SKILL.md into { meta, body }. */
function parseKitSkill(source) {
  const m = source.match(/^\s*---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  const meta = {};
  if (m) {
    for (const line of m[1].split(/\r?\n/)) {
      const kv = line.match(/^([A-Za-z][\w-]*)\s*:\s*(.*)$/);
      if (kv) meta[kv[1]] = kv[2].trim().replace(/^["']|["']$/g, "");
    }
  }
  return { meta, body: (m ? m[2] : source).trim() };
}

const oneLine = (s) => s.replace(/\s+/g, " ").trim();

/** Builds a skill source in our format. */
function makeSkill({ name, description, mode, body, origin }) {
  return [
    "---",
    `name: ${name}`,
    "scope: platform",
    "enforcement: advisory",
    ...(mode ? [`mode: ${mode}`] : []),
    `origin: penpot-ai-kit${origin ? `/${origin}` : ""}`,
    `description: ${oneLine(description)}`,
    "---",
    "",
    body,
  ].join("\n");
}

const skills = [];

// 1. every kit skill, mode taken from the kit manifest
for (const entry of kitManifest.skills) {
  const path = join(kitDir, entry.path);
  const { meta, body } = parseKitSkill(readFileSync(path, "utf8"));
  skills.push(
    makeSkill({
      name: entry.id,
      description: meta.description || entry.description,
      mode: entry.mode ?? meta["mode-default"],
      body,
      origin: entry.path,
    }),
  );
}

// 2. load-bearing shared docs every kit skill links to
const sharedDocs = [
  {
    file: "plugin-api-gotchas.md",
    name: "penpot-plugin-api-gotchas",
    description:
      "Hard-won facts about the Penpot Plugin API that models get wrong by default (immutable style arrays, applyToken async/chunking, resize vs width/height, layout vs x/y, token set/theme creation). MUST be read before the first canvas-mutating execute_code of a session.",
  },
  {
    file: "naming-conventions.md",
    name: "penpot-naming-conventions",
    description:
      "Single source of truth for names: dot-notation design tokens (W3C DTCG), PascalCase components, Property=Value variants, semantic kebab-case layers.",
  },
  {
    file: "modes-and-policies.md",
    name: "penpot-operating-modes",
    description:
      "The three operating modes (suggest, apply-with-review, auto-fix), the auto-fix safe set, and the never-auto-fix list that governs how much may happen without asking the user.",
  },
  {
    file: "penpot-mcp-tool-reference.md",
    name: "penpot-mcp-tool-reference",
    description:
      "Reference for the four official Penpot MCP tools (high_level_overview, penpot_api_info, execute_code, export_shape) — for agents connected through the MCP server.",
  },
];

for (const doc of sharedDocs) {
  const body = readFileSync(join(kitDir, "shared", doc.file), "utf8").trim();
  skills.push(
    makeSkill({
      name: doc.name,
      description: doc.description,
      body,
      origin: `shared/${doc.file}`,
    }),
  );
}

// emit the shared skills-core module (bundled by the panel, the plugin and the MCP server)
const ts = [
  "/**",
  " * GENERATED by ai-skills/scripts/import-aikit.mjs — do not edit by hand.",
  " * Platform-scope skills imported from the official penpot-ai-kit",
  " * (https://github.com/penpot/penpot-ai-kit).",
  " */",
  "",
  `export const AIKIT_PLATFORM_SKILLS: string[] = ${JSON.stringify(skills, null, 2)};`,
  "",
].join("\n");
writeFileSync(join(here, "..", "..", "skills-core", "src", "aikit.gen.ts"), ts);

console.log(
  `imported ${kitManifest.skills.length} skills + ${sharedDocs.length} shared docs from ${kitDir}`,
);
