;; This Source Code Form is subject to the terms of the Mozilla Public
;; License, v. 2.0. If a copy of the MPL was not distributed with this
;; file, You can obtain one at http://mozilla.org/MPL/2.0/.
;;
;; Copyright (c) KALEIDOS INC Sucursal en España SL

(ns app.migrations.clj.migration-0153
  "Seeds the app-level (instance-wide) design skills from the official
  penpot-ai-kit set. The seed resource is generated by
  ai-skills/scripts/generate-skill-seed.mjs from the committed kit import."
  (:require
   [app.common.json :as json]
   [app.db :as db]
   [clojure.java.io :as io]))

(defn- get-seed-rows
  []
  (-> (io/resource "app/design-skills-seed.json")
      (slurp)
      (json/decode :key-fn keyword)))

(defn migrate
  [conn]
  (let [total (->> ["select count(*) as total from design_skill where team_id is null"]
                   (db/exec-one! conn)
                   (:total))]
    (when (zero? total)
      (doseq [row (get-seed-rows)]
        (db/insert! conn :design-skill
                    {:name (:name row)
                     :kind (:kind row)
                     :enforcement (:enforcement row)
                     :is-mandatory (boolean (:is-mandatory row))
                     :trigger-on (:trigger-on row)
                     :description (:description row)
                     :body (:body row)
                     :origin (:origin row)})))))
